// frontend/src/pages/Alerts.jsx
import { useState, useEffect, useRef } from 'react';
import * as api from '../api.js';
import Badge from '../components/Badge.jsx';
import { Toggle, PageHeader, SkeletonRows, EmptyState, LoadingError } from '../components/Shared.jsx';

export default function Alerts() {
  const [rules, setRules] = useState([]);
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [toasts, setToasts] = useState([]);
  const prevLen = useRef(0);

  const fetch = async () => { try { const [r, h] = await Promise.all([api.alerts.rules.list(), api.alerts.history.list()]); setRules(r); setHistory(h); setError(null); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { fetch(); }, []);

  useEffect(() => {
    if (history.length > prevLen.current && history.length > 0 && !history[0].acknowledged) {
      const a = history[0];
      setToasts((p) => [...p, { id: a.id, msg: a.message || a.condition, sever: a.severity }]);
      setTimeout(() => setToasts((p) => p.filter((t) => t.id !== a.id)), 8000);
    }
    prevLen.current = history.length;
  }, [history]);

  const acknowledge = async (id) => { try { await api.alerts.history.acknowledge(id); setHistory((p) => p.map((a) => a.id === id ? { ...a, acknowledged: true } : a)); } catch {} };
  const toggleRule = async (r) => { try { const updated = { ...r, enabled: !r.enabled }; await api.alerts.rules.create(updated); setRules((p) => p.map((x) => x.id === r.id ? updated : x)); } catch {} };

  const unread = history.filter((a) => !a.acknowledged).length;

  return (
    <div className="fade-in">
      <PageHeader title="Alerts" subtitle={`${unread} unacknowledged`}>
        <button className="btn btn-primary" onClick={() => history.forEach((a) => acknowledge(a.id))}>Acknowledge All</button>
      </PageHeader>

      {toasts.map((t) => (
        <div key={t.id} className="toast">
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
            <span style={{ color: 'var(--red)', fontWeight: 700, fontSize: 12 }}>🚨 {t.sever?.toUpperCase()} ALERT</span>
            <button onClick={() => setToasts((p) => p.filter((x) => x.id !== t.id))} style={{ background: 'none', border: 'none', color: 'var(--text-sec)', cursor: 'pointer', padding: 0 }}>✕</button>
          </div>
          <div style={{ fontSize: 13, marginBottom: 4 }}>{t.msg}</div>
          <div className="progress"><div className="progress-bar" /></div>
        </div>
      ))}

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
        <div className="card">
          <div style={{ color: 'var(--text-sec)', fontSize: 12, marginBottom: 12 }}>📋 Alert Rules</div>
          {loading ? <SkeletonRows count={3} cols={4} /> : error ? <LoadingError message={error} onRetry={fetch} /> : (
            rules.map((r) => (
              <div key={r.id} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '8px 0', borderBottom: '1px solid var(--bg-border)' }}>
                <div>
                  <div style={{ fontSize: 13 }}>{r.name}</div>
                  <div className="cell-mono cell-dim" style={{ fontSize: 11 }}>{r.condition?.BlockedIpThreshold ? `≥${r.condition.BlockedIpThreshold.count} IPs in ${r.condition.BlockedIpThreshold.window_secs}s` : r.condition?.ConnectionFlood ? `≥${r.condition.ConnectionFlood.rate_per_second} conn/s` : JSON.stringify(r.condition)}</div>
                </div>
                <Toggle checked={r.enabled} onChange={() => toggleRule(r)} />
              </div>
            ))
          )}
        </div>

        <div className="card">
          <div style={{ color: 'var(--text-sec)', fontSize: 12, marginBottom: 12 }}>📜 Alert History</div>
          {history.length === 0 ? <EmptyState msg="No alerts fired yet." /> : (
            history.slice(0, 20).map((a) => (
              <div key={a.id} style={{ display: 'flex', gap: 8, padding: '8px 0', borderBottom: '1px solid var(--bg-border)', alignItems: 'center', borderLeft: `3px solid ${a.acknowledged ? 'var(--text-muted)' : 'var(--red)'}`, paddingLeft: 8 }}>
                <span>{a.severity === 'critical' ? '🔴' : a.severity === 'warning' ? '🟡' : '🟢'}</span>
                <div style={{ flex: 1 }}>
                  <div style={{ fontSize: 12 }}>{a.message || a.condition}</div>
                  <div className="cell-mono cell-dim" style={{ fontSize: 11 }}>{new Date(a.timestamp).toLocaleString()} — {a.rule_name}</div>
                </div>
                {!a.acknowledged ? (
                  <button className="btn" style={{ padding: '4px 8px', fontSize: 11 }} onClick={() => acknowledge(a.id)}>✓ Ack</button>
                ) : <span style={{ color: 'var(--green)', fontSize: 16 }}>✓</span>}
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
}

// frontend/src/routes/alerts/+page.svelte
<script>
  import { onMount } from 'svelte';
  import { apiFetch } from '$lib/stores/auth';

  let alertHistory = $state([]);
  let alertRules = $state([]);
  let loading = $state(true);
  let error = $state('');

  onMount(async () => {
    try {
      const [history, rules] = await Promise.all([
        apiFetch('/alerts/history').catch(() => []),
        apiFetch('/alerts/rules').catch(() => []),
      ]);
      alertHistory = Array.isArray(history) ? history : [];
      alertRules = Array.isArray(rules) ? rules : [];
    } catch (e) {
      error = e.message;
    } finally {
      loading = false;
    }
  });

  async function acknowledge(alertId) {
    try {
      await apiFetch('/alerts/history/' + alertId + '/ack', { method: 'POST' });
      alertHistory = alertHistory.map((a) => a.id === alertId ? { ...a, acknowledged: true } : a);
    } catch (e) {
      alert('Error: ' + e.message);
    }
  }

  function severityBadge(sev) {
    if (sev === 'critical' || sev === 'high') return 'deny';
    if (sev === 'warning' || sev === 'medium') return 'warn';
    return 'info';
  }
</script>

<div class="flex justify-between items-center mb-4 animate-in">
  <div>
    <h1 style="font-family:var(--font-display);font-size:18px;color:var(--text-heading);letter-spacing:2px;text-transform:uppercase;">
      🔔 Alerts
    </h1>
    <span style="font-size:10px;color:var(--text-muted);letter-spacing:1px;">
      {alertHistory.length} ALERTS · {alertRules.length} RULES
    </span>
  </div>
</div>

{#if loading}
  <div style="text-align:center;padding:40px;color:var(--text-muted);">LOADING...</div>
{:else if error}
  <div class="card mb-4">
    <p style="color:var(--red);">⚠ {error}</p>
  </div>
{:else}
  <div class="grid grid-cols-2 gap-4 mb-4 animate-in">
    <div class="card">
      <div class="card-header">
        <div class="indicator" style="background:var(--red);box-shadow:0 0 8px var(--red);"></div>
        <h2>Alert Rules ({alertRules.length})</h2>
      </div>
      <div style="max-height: 400px; overflow-y: auto;">
        {#if alertRules.length === 0}
          <p style="color:var(--text-muted);font-size:12px;padding:16px 0;text-align:center;">NO ALERT RULES CONFIGURED</p>
        {:else}
          {#each alertRules as rule}
            <div style="display:flex;align-items:center;justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--border-dim);font-size:12px;">
              <span style="color:var(--text-bright);font-family:var(--font-mono);">{rule.name || rule.id}</span>
              <span class="badge {severityBadge(rule.severity)}">{rule.severity || 'info'}</span>
              <span class="badge" class:on={rule.enabled} class:off={!rule.enabled}>
                {rule.enabled ? 'ON' : 'OFF'}
              </span>
            </div>
          {/each}
        {/if}
      </div>
    </div>

    <div class="card">
      <div class="card-header">
        <div class="indicator" style="background:var(--yellow);box-shadow:0 0 8px var(--yellow);"></div>
        <h2>Alert History ({alertHistory.length})</h2>
      </div>
      <div style="max-height: 400px; overflow-y: auto;">
        {#if alertHistory.length === 0}
          <p style="color:var(--text-muted);font-size:12px;padding:16px 0;text-align:center;">NO ALERTS — all clear</p>
        {:else}
          {#each alertHistory.slice(0, 50) as al}
            <div style="display:flex;align-items:center;gap:8px;padding:8px 0;border-bottom:1px solid var(--border-dim);font-size:11px;">
              <span class="badge {severityBadge(al.severity)}">{al.severity || 'info'}</span>
              <span style="color:var(--text-bright);flex:1;font-family:var(--font-mono);">{al.message || al.rule_name || al.id}</span>
              <span style="color:var(--text-muted);font-size:10px;">{al.timestamp ? new Date(al.timestamp).toLocaleTimeString() : ''}</span>
              {#if !al.acknowledged}
                <button class="btn btn-primary" style="padding:2px 8px;font-size:10px;" onclick={() => acknowledge(al.id)}>
                  ACK
                </button>
              {:else}
                <span class="badge on">ACKED</span>
              {/if}
            </div>
          {/each}
        {/if}
      </div>
    </div>
  </div>

  <div class="card animate-in">
    <table class="data-table">
      <thead>
        <tr>
          <th>Time</th>
          <th>Severity</th>
          <th>Message</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        {#each alertHistory as al}
          <tr>
            <td style="color:var(--text-muted);font-size:11px;">
              {al.timestamp ? new Date(al.timestamp).toLocaleString() : '—'}
            </td>
            <td>
              <span class="badge {severityBadge(al.severity)}">{al.severity || 'info'}</span>
            </td>
            <td style="color:var(--text-bright);">{al.message || al.rule_name || '—'}</td>
            <td>
              {#if al.acknowledged}
                <span class="badge on">ACKED</span>
              {:else}
                <span class="badge warn">PENDING</span>
              {/if}
            </td>
          </tr>
        {:else}
          <tr>
            <td colspan="4" style="text-align:center;padding:32px;color:var(--text-muted);">
              No alert history
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
{/if}
