// frontend/src/routes/rules/+page.svelte
<script>
  import { onMount } from 'svelte';
  import { apiFetch } from '$lib/stores/auth';

  let rules = $state([]);
  let showForm = $state(false);
  let form = $state({ name: '', action: 'deny', direction: 'inbound', src_cidr: '', dst_cidr: '', protocol: '', src_port: '', dst_port: '', priority: 100, enabled: true });

  let search = $state('');
  let selected = $state(new Set());
  let currentPage = $state(1);
  const pageSize = 20;

  const ruleTemplates = [
    { name: 'Block SSH from WAN', action: 'deny', direction: 'inbound', src_cidr: '', dst_cidr: '', protocol: 'tcp', dst_port: '22', priority: 100 },
    { name: 'Allow HTTPS', action: 'allow', direction: 'inbound', src_cidr: '', dst_cidr: '', protocol: 'tcp', dst_port: '443', priority: 100 },
    { name: 'Block All Inbound', action: 'deny', direction: 'inbound', src_cidr: '0.0.0.0/0', dst_cidr: '', protocol: '', dst_port: '', priority: 100 },
    { name: 'Allow LAN', action: 'allow', direction: 'inbound', src_cidr: '10.0.0.0/8', dst_cidr: '', protocol: '', dst_port: '', priority: 100 },
    { name: 'Rate Limit DNS', action: 'rate-limit:100pps', direction: 'outbound', src_cidr: '', dst_cidr: '', protocol: 'udp', dst_port: '53', priority: 100 },
  ];

  let filtered = $derived(() => {
    const q = search.toLowerCase();
    if (!q) return rules;
    return rules.filter((r) =>
      (r.name || '').toLowerCase().includes(q) ||
      (r.src_cidr || '').toLowerCase().includes(q) ||
      (r.dst_cidr || '').toLowerCase().includes(q) ||
      (r.action || '').toLowerCase().includes(q) ||
      (r.protocol || '').toLowerCase().includes(q)
    );
  })();

  let totalPages = $derived(Math.max(1, Math.ceil(filtered.length / pageSize)));
  let paged = $derived(filtered.slice((currentPage - 1) * pageSize, currentPage * pageSize));

  $effect(() => {
    if (currentPage > totalPages) currentPage = totalPages;
  });

  let allSelected = $derived(paged.length > 0 && paged.every((r) => selected.has(r.id)));
  let anySelected = $derived(selected.size > 0);

  function toggleAll() {
    if (allSelected) {
      for (const r of paged) selected.delete(r.id);
    } else {
      for (const r of paged) selected.add(r.id);
    }
    selected = new Set(selected);
  }

  function toggleOne(id) {
    const next = new Set(selected);
    if (next.has(id)) next.delete(id); else next.add(id);
    selected = next;
  }

  function applyTemplate(e) {
    const key = e.target.value;
    if (!key) return;
    const t = ruleTemplates[parseInt(key)];
    if (t) form = { ...t };
    e.target.value = '';
  }

  async function loadRules() {
    try { rules = await apiFetch('/rules'); selected = new Set(); } catch (e) { console.error(e); }
  }

  onMount(loadRules);

  async function createRule() {
    try {
      const payload = {
        name: form.name,
        action: form.action,
        direction: form.direction,
        src_cidr: form.src_cidr || null,
        dst_cidr: form.dst_cidr || null,
        src_port: form.src_port ? parseInt(form.src_port) : null,
        dst_port: form.dst_port ? parseInt(form.dst_port) : null,
        protocol: form.protocol || null,
        priority: form.priority,
        enabled: form.enabled,
      };
      await apiFetch('/rules', { method: 'POST', body: JSON.stringify(payload) });
      form = { name: '', action: 'deny', direction: 'inbound', src_cidr: '', dst_cidr: '', protocol: '', src_port: '', dst_port: '', priority: 100, enabled: true };
      showForm = false;
      await loadRules();
    } catch (e) { alert('Error: ' + e.message); }
  }

  async function deleteRule(id) {
    if (!confirm('DROP rule ' + id + '?')) return;
    try {
      await apiFetch('/rules/' + id, { method: 'DELETE' });
      selected.delete(id); selected = new Set(selected);
      await loadRules();
    } catch (e) { alert('Error: ' + e.message); }
  }

  async function deleteSelected() {
    if (selected.size === 0) return;
    if (!confirm('DROP ' + selected.size + ' selected rules?')) return;
    try {
      await Promise.all([...selected].map((id) => apiFetch('/rules/' + id, { method: 'DELETE' })));
      await loadRules();
    } catch (e) { alert('Error: ' + e.message); }
  }

  async function toggleRule(id, enabled) {
    try {
      const rule = rules.find((r) => r.id === id);
      if (!rule) return;
      await apiFetch('/rules/' + id, { method: 'PUT', body: JSON.stringify({ ...rule, enabled }) });
      await loadRules();
    } catch (e) { alert('Error: ' + e.message); }
  }

  function exportJSON() {
    const blob = new Blob([JSON.stringify(rules, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = 'argus-rules-export.json'; a.click();
    URL.revokeObjectURL(url);
  }

  function importJSON() {
    const input = document.createElement('input');
    input.type = 'file'; input.accept = '.json';
    input.onchange = async (e) => {
      const file = e.target.files[0];
      if (!file) return;
      try {
        const text = await file.text();
        const data = JSON.parse(text);
        const items = Array.isArray(data) ? data : [data];
        let imported = 0;
        for (const item of items) {
          await apiFetch('/rules', { method: 'POST', body: JSON.stringify(item) });
          imported++;
        }
        alert('Imported ' + imported + ' rules.');
        await loadRules();
      } catch (e) { alert('Import error: ' + e.message); }
    };
    input.click();
  }
</script>

<div class="flex justify-between items-center mb-4 animate-in">
  <div>
    <h1 style="font-family:var(--font-display);font-size:18px;color:var(--text-heading);letter-spacing:2px;text-transform:uppercase;">
      ⚙ Firewall Rules
    </h1>
    <span style="font-size:10px;color:var(--text-muted);letter-spacing:1px;">{rules.length} RULES LOADED</span>
  </div>
  <div class="flex gap-2">
    <button class="btn btn-ghost" onclick={exportJSON}>📥 EXPORT JSON</button>
    <button class="btn btn-ghost" onclick={importJSON}>📤 IMPORT JSON</button>
    <button class="btn btn-primary" onclick={() => showForm = !showForm}>
      {showForm ? '✕ CANCEL' : '+ ADD RULE'}
    </button>
  </div>
</div>

{#if showForm}
  <div class="card mb-4 animate-in">
    <div class="card-header">
      <div class="indicator" style="background:var(--yellow);"></div>
      <h2>New Rule — Configuration</h2>
    </div>
    <div class="grid grid-cols-4 gap-4">
      <div class="col-span-2">
        <label style="font-size:10px;text-transform:uppercase;letter-spacing:1px;color:var(--text-muted);display:block;margin-bottom:4px;">Rule Name</label>
        <input class="input" bind:value={form.name} placeholder="e.g. block-ssh-from-wan">
      </div>
      <div>
        <label style="font-size:10px;text-transform:uppercase;letter-spacing:1px;color:var(--text-muted);display:block;margin-bottom:4px;">Action</label>
        <select class="select" bind:value={form.action}>
          <option value="deny">DENY</option>
          <option value="allow">ALLOW</option>
          <option value="rate-limit:100pps">RATE-LIMIT 100pps</option>
        </select>
      </div>
      <div>
        <label style="font-size:10px;text-transform:uppercase;letter-spacing:1px;color:var(--text-muted);display:block;margin-bottom:4px;">Direction</label>
        <select class="select" bind:value={form.direction}>
          <option value="inbound">INBOUND</option>
          <option value="outbound">OUTBOUND</option>
          <option value="forward">FORWARD</option>
        </select>
      </div>
      <div>
        <label style="font-size:10px;text-transform:uppercase;letter-spacing:1px;color:var(--text-muted);display:block;margin-bottom:4px;">Template</label>
        <select class="select" onchange={applyTemplate}>
          <option value="">— select template —</option>
          {#each ruleTemplates as t, i}
            <option value={i}>{t.name}</option>
          {/each}
        </select>
      </div>
      <div>
        <label style="font-size:10px;text-transform:uppercase;letter-spacing:1px;color:var(--text-muted);display:block;margin-bottom:4px;">Source CIDR</label>
        <input class="input" bind:value={form.src_cidr} placeholder="0.0.0.0/0">
      </div>
      <div>
        <label style="font-size:10px;text-transform:uppercase;letter-spacing:1px;color:var(--text-muted);display:block;margin-bottom:4px;">Dest CIDR</label>
        <input class="input" bind:value={form.dst_cidr} placeholder="10.0.0.0/8">
      </div>
      <div>
        <label style="font-size:10px;text-transform:uppercase;letter-spacing:1px;color:var(--text-muted);display:block;margin-bottom:4px;">Protocol</label>
        <input class="input" bind:value={form.protocol} placeholder="tcp/udp/icmp">
      </div>
      <div>
        <label style="font-size:10px;text-transform:uppercase;letter-spacing:1px;color:var(--text-muted);display:block;margin-bottom:4px;">Port</label>
        <input class="input" bind:value={form.dst_port} placeholder="e.g. 22 or 443">
      </div>
      <div class="col-span-4 flex gap-4" style="padding-top:12px;">
        <button class="btn btn-primary" onclick={createRule}>DEPLOY RULE</button>
        <button class="btn btn-ghost" onclick={() => showForm = false}>DISCARD</button>
      </div>
    </div>
  </div>
{/if}

<div class="flex gap-4 mb-4 animate-in flex-wrap items-center">
  <div style="flex:1;max-width:400px;">
    <input class="input" bind:value={search} placeholder="Search rules by name, CIDR, action, protocol...">
  </div>
  {#if anySelected}
    <button class="btn btn-danger" onclick={deleteSelected}>
      DELETE {selected.size} SELECTED
    </button>
  {/if}
  {#if totalPages > 1}
    <div class="pagination ml-2">
      <button disabled={currentPage <= 1} onclick={() => currentPage = 1}>«</button>
      <button disabled={currentPage <= 1} onclick={() => currentPage--}>‹</button>
      {#each Array(totalPages) as _, i}
        {#if i < 3 || i >= totalPages - 3 || Math.abs(i + 1 - currentPage) <= 1}
          <button class:active={currentPage === i + 1} onclick={() => currentPage = i + 1}>{i + 1}</button>
        {:else if i === 3 || i === totalPages - 4}
          <span>…</span>
        {/if}
      {/each}
      <button disabled={currentPage >= totalPages} onclick={() => currentPage++}>›</button>
      <button disabled={currentPage >= totalPages} onclick={() => currentPage = totalPages}>»</button>
    </div>
  {/if}
</div>

<div class="card animate-in">
  <table class="data-table">
    <thead>
      <tr>
        <th style="width:30px;"><input class="checkbox" type="checkbox" checked={allSelected} onchange={toggleAll}></th>
        <th>#</th>
        <th>Name</th>
        <th>Action</th>
        <th>Source</th>
        <th>Dest</th>
        <th>Proto</th>
        <th>Dir</th>
        <th>Status</th>
        <th class="text-right">Ops</th>
      </tr>
    </thead>
    <tbody>
      {#each paged as rule}
        <tr>
          <td><input class="checkbox" type="checkbox" checked={selected.has(rule.id)} onchange={() => toggleOne(rule.id)}></td>
          <td style="color:var(--text-muted);">{rule.priority}</td>
          <td style="color:var(--text-bright);">{rule.name}</td>
          <td>
            {#if rule.action === 'deny'}
              <span class="badge deny">DENY</span>
            {:else if rule.action && rule.action.startsWith('rate-limit')}
              <span class="badge warn">LIMIT</span>
            {:else}
              <span class="badge allow">ALLOW</span>
            {/if}
          </td>
          <td style="color:var(--text-body);">{rule.src_cidr || '*'}</td>
          <td style="color:var(--text-body);">{rule.dst_cidr || '*'}</td>
          <td style="color:var(--text-muted);">{rule.protocol || 'any'}</td>
          <td style="color:var(--text-muted);">{rule.direction}</td>
          <td>
            <button
              class="badge"
              class:on={rule.enabled}
              class:off={!rule.enabled}
              style="cursor:pointer;border:none;"
              onclick={() => toggleRule(rule.id, !rule.enabled)}
              title="Toggle enable/disable"
            >
              {rule.enabled ? 'ON' : 'OFF'}
            </button>
          </td>
          <td class="text-right">
            <button class="btn btn-danger" style="padding:2px 8px;font-size:10px;" onclick={() => deleteRule(rule.id)}>
              DEL
            </button>
          </td>
        </tr>
      {:else}
        <tr>
          <td colspan="10" style="text-align:center;padding:32px;color:var(--text-muted);">
            {search ? 'NO RULES MATCH YOUR SEARCH' : "NO RULES DEFINED — Press '+ ADD RULE' to create your first firewall rule"}
          </td>
        </tr>
      {/each}
    </tbody>
  </table>
</div>

// frontend/src/pages/Rules.jsx
import { useState, useEffect, useMemo } from 'react';
import * as api from '../api.js';
import Badge from '../components/Badge.jsx';
import { Toggle, Modal, PageHeader, SkeletonRows, EmptyState, LoadingError, Field } from '../components/Shared.jsx';

export default function Rules() {
  const [rules, setRules] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [search, setSearch] = useState('');
  const [filterAction, setFilterAction] = useState('all');
  const [filterDir, setFilterDir] = useState('all');
  const [filterStatus, setFilterStatus] = useState('all');
  const [selected, setSelected] = useState(new Set());
  const [modal, setModal] = useState(false);
  const [simOpen, setSimOpen] = useState(false);
  const [simResult, setSimResult] = useState(null);
  const [form, setForm] = useState({ name: '', action: 'allow', direction: 'inbound', src_cidr: '', dst_cidr: '', src_port: '', dst_port: '', protocol: 'any', priority: 100, enabled: true, description: '' });
  const [errors, setErrors] = useState({});
  const [submitting, setSubmitting] = useState(false);

  const fetchRules = async () => { setLoading(true); try { setRules(await api.rules.list()); setError(null); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { fetchRules(); }, []);

  const filtered = useMemo(() => rules.filter((r) => {
    const m = !search || r.name?.toLowerCase().includes(search.toLowerCase()) || r.src_cidr?.includes(search) || r.dst_cidr?.includes(search);
    const a = filterAction === 'all' || r.action === filterAction || r.action?.startsWith(filterAction);
    const d = filterDir === 'all' || r.direction === filterDir;
    const s = filterStatus === 'all' || (filterStatus === 'enabled' ? r.enabled : !r.enabled);
    return m && a && d && s;
  }), [rules, search, filterAction, filterDir, filterStatus]);

  const validate = () => {
    const e = {};
    if (!form.name.trim()) e.name = 'Required';
    if (form.src_cidr && !/^(\d{1,3}\.){3}\d{1,3}\/\d{1,2}$/.test(form.src_cidr)) e.src_cidr = 'Invalid CIDR';
    if (form.dst_cidr && !/^(\d{1,3}\.){3}\d{1,3}\/\d{1,2}$/.test(form.dst_cidr)) e.dst_cidr = 'Invalid CIDR';
    const sp = Number(form.src_port);
    if (form.src_port && (isNaN(sp) || sp < 0 || sp > 65535)) e.src_port = '0–65535';
    const dp = Number(form.dst_port);
    if (form.dst_port && (isNaN(dp) || dp < 0 || dp > 65535)) e.dst_port = '0–65535';
    setErrors(e);
    return Object.keys(e).length === 0;
  };

  const handleCreate = async () => {
    if (!validate()) return;
    setSubmitting(true);
    try { await api.rules.create(form); fetchRules(); setModal(false); setForm({ name: '', action: 'allow', direction: 'inbound', src_cidr: '', dst_cidr: '', src_port: '', dst_port: '', protocol: 'any', priority: 100, enabled: true, description: '' }); }
    catch (e) { setErrors({ form: e.message }); }
    finally { setSubmitting(false); }
  };

  const handleDelete = async (id) => { try { await api.rules.delete(id); fetchRules(); } catch (e) { /* silent */ } };
  const handleToggle = async (r) => { try { await api.rules.update(r.id, { ...r, enabled: !r.enabled }); fetchRules(); } catch (e) { /* silent */ } };

  const toggleAll = () => setSelected((p) => p.size === filtered.length ? new Set() : new Set(filtered.map((r) => r.id)));
  const toggleSelect = (id) => setSelected((p) => { const n = new Set(p); n.has(id) ? n.delete(id) : n.add(id); return n; });

  const handleSimulate = async (e) => {
    e.preventDefault();
    const fd = Object.fromEntries(new FormData(e.target));
    try { setSimResult(await api.rules.simulate(fd)); } catch (err) { setSimResult({ matched: false, rule_name: null, action: null }); }
  };

  return (
    <div className="fade-in">
      <PageHeader title="Firewall Rules" subtitle={`${rules.length} rule${rules.length !== 1 ? 's' : ''}`}>
        <button className="btn" onClick={() => setSimOpen(!simOpen)}>🔬 Simulator</button>
        <button className="btn btn-primary" onClick={() => setModal(true)}>+ New Rule</button>
      </PageHeader>

      <div className="panel" style={{ padding: 12 }}>
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'center' }}>
          <input className="input-box" style={{ width: 200 }} placeholder="Search..." value={search} onChange={(e) => setSearch(e.target.value)} />
          <select className="select-box" value={filterAction} onChange={(e) => setFilterAction(e.target.value)}>
            {['all','allow','deny','rate-limit'].map((v) => <option key={v} value={v}>{v === 'all' ? 'All Actions' : v}</option>)}
          </select>
          <select className="select-box" value={filterDir} onChange={(e) => setFilterDir(e.target.value)}>
            {['all','inbound','outbound','forward'].map((v) => <option key={v} value={v}>{v === 'all' ? 'All Directions' : v}</option>)}
          </select>
          <select className="select-box" value={filterStatus} onChange={(e) => setFilterStatus(e.target.value)}>
            <option value="all">All Status</option>
            <option value="enabled">Enabled</option>
            <option value="disabled">Disabled</option>
          </select>
          {selected.size > 0 && (
            <span style={{ padding: '4px 8px', background: 'var(--bg-elevated)', borderRadius: 6, color: 'var(--text-sec)', fontSize: 11 }}>{selected.size} selected</span>
          )}
          <a href="/api/v1/rules/export/json" className="btn" style={{ marginLeft: 'auto' }}>Export JSON</a>
        </div>
      </div>

      {simOpen && (
        <div className="card" style={{ marginBottom: 12 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 12 }}>
            <span style={{ color: 'var(--text-sec)', fontSize: 12 }}>🔬 Packet Simulator</span>
            <button onClick={() => setSimOpen(false)} style={{ background: 'none', border: 'none', color: 'var(--text-sec)', cursor: 'pointer' }}>✕</button>
          </div>
          <form onSubmit={handleSimulate} style={{ display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'flex-end' }}>
            <Field label="Src IP"><input name="src_ip" className="input-box" style={{ width: 140, fontFamily: 'var(--font-mono)' }} required /></Field>
            <Field label="Dst IP"><input name="dst_ip" className="input-box" style={{ width: 140, fontFamily: 'var(--font-mono)' }} required /></Field>
            <Field label="Src Port"><input name="src_port" className="input-box" style={{ width: 80, fontFamily: 'var(--font-mono)' }} /></Field>
            <Field label="Dst Port"><input name="dst_port" className="input-box" style={{ width: 80, fontFamily: 'var(--font-mono)' }} /></Field>
            <Field label="Protocol"><select name="protocol" className="select-box"><option value="any">Any</option><option value="tcp">TCP</option><option value="udp">UDP</option><option value="icmp">ICMP</option></select></Field>
            <Field label="Direction"><select name="direction" className="select-box" required><option value="inbound">Inbound</option><option value="outbound">Outbound</option><option value="forward">Forward</option></select></Field>
            <button type="submit" className="btn btn-primary">Simulate</button>
          </form>
          {simResult && (
            <div style={{ marginTop: 12, padding: 12, borderRadius: 8, background: 'var(--bg-elevated)', border: `1px solid ${simResult.matched ? (simResult.action?.startsWith('allow') ? 'var(--green)' : simResult.action?.startsWith('deny') ? 'var(--red)' : 'var(--yellow)') : 'var(--text-muted)'}` }}>
              <div style={{ fontSize: 13 }}>
                {simResult.matched ? <>Matched: <strong>{simResult.rule_name}</strong> → <strong>{simResult.action}</strong></> : 'No rule matched — packet would PASS'}
              </div>
            </div>
          )}
        </div>
      )}

      <div className="panel" style={{ overflow: 'hidden' }}>
        {loading ? <SkeletonRows count={4} cols={11} /> : error ? <LoadingError message={error} onRetry={fetchRules} /> : (
          <table>
            <thead><tr>{['','#','Name','Action','Dir','Src CIDR','Dst CIDR','Proto','Port','Status',''].map((h) => <th key={h}>{h === '' ? <input type="checkbox" checked={selected.size === filtered.length && filtered.length > 0} onChange={toggleAll} style={{ accentColor: 'var(--cyan)' }} /> : h}</th>)}</tr></thead>
            <tbody>
              {filtered.length === 0 ? <tr><td colSpan={11}><EmptyState msg="No rules found." /></td></tr> : (
                filtered.map((r) => (
                  <tr key={r.id} style={{ background: simResult?.matched && simResult.rule_id === r.id ? 'rgba(0,212,255,0.08)' : undefined }}>
                    <td><input type="checkbox" checked={selected.has(r.id)} onChange={() => toggleSelect(r.id)} style={{ accentColor: 'var(--cyan)' }} /></td>
                    <td className="cell-mono" style={{ color: 'var(--text-muted)' }}>{r.priority}</td>
                    <td>{r.name}</td>
                    <td><Badge variant={r.action?.split(':')[0] || r.action}>{r.action}</Badge></td>
                    <td><Badge variant={r.direction}>{r.direction}</Badge></td>
                    <td className="cell-mono cell-dim">{r.src_cidr || '*'}</td>
                    <td className="cell-mono cell-dim">{r.dst_cidr || '*'}</td>
                    <td className="cell-mono cell-dim">{r.protocol || 'any'}</td>
                    <td className="cell-mono cell-dim">{r.dst_port || r.src_port || '*'}</td>
                    <td><Toggle checked={r.enabled} onChange={() => handleToggle(r)} /></td>
                    <td><button className="btn" style={{ padding: '4px 8px', fontSize: 11, color: 'var(--red)' }} onClick={() => handleDelete(r.id)}>🗑️</button></td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        )}
      </div>

      <Modal open={modal} onClose={() => setModal(false)} title="New Firewall Rule">
        <div className="form-row">
          <Field label="Name *" error={errors.name}><input className="input-box" value={form.name} onChange={(e) => { setForm({ ...form, name: e.target.value }); setErrors({}); }} /></Field>
          <Field label="Action *"><select className="select-box" value={form.action} onChange={(e) => setForm({ ...form, action: e.target.value })} style={{ width: '100%' }}><option value="allow">Allow</option><option value="deny">Deny</option><option value="rate-limit">Rate-Limit</option></select></Field>
          <Field label="Direction *"><select className="select-box" value={form.direction} onChange={(e) => setForm({ ...form, direction: e.target.value })} style={{ width: '100%' }}><option value="inbound">Inbound</option><option value="outbound">Outbound</option><option value="forward">Forward</option></select></Field>
          <Field label="Protocol"><select className="select-box" value={form.protocol} onChange={(e) => setForm({ ...form, protocol: e.target.value })} style={{ width: '100%' }}><option value="any">Any</option><option value="tcp">TCP</option><option value="udp">UDP</option><option value="icmp">ICMP</option></select></Field>
          <Field label="Src CIDR" error={errors.src_cidr}><input className="input-box" value={form.src_cidr} onChange={(e) => { setForm({ ...form, src_cidr: e.target.value }); setErrors({}); }} placeholder="10.0.0.0/8" style={{ fontFamily: 'var(--font-mono)' }} /></Field>
          <Field label="Dst CIDR" error={errors.dst_cidr}><input className="input-box" value={form.dst_cidr} onChange={(e) => { setForm({ ...form, dst_cidr: e.target.value }); setErrors({}); }} placeholder="0.0.0.0/0" style={{ fontFamily: 'var(--font-mono)' }} /></Field>
          <Field label="Src Port" error={errors.src_port}><input className="input-box" value={form.src_port} onChange={(e) => { setForm({ ...form, src_port: e.target.value }); setErrors({}); }} style={{ fontFamily: 'var(--font-mono)' }} /></Field>
          <Field label="Dst Port" error={errors.dst_port}><input className="input-box" value={form.dst_port} onChange={(e) => { setForm({ ...form, dst_port: e.target.value }); setErrors({}); }} style={{ fontFamily: 'var(--font-mono)' }} /></Field>
          <Field label="Priority"><input className="input-box" type="number" value={form.priority} onChange={(e) => setForm({ ...form, priority: Number(e.target.value) || 0 })} /></Field>
          <Field label="Enabled"><Toggle checked={form.enabled} onChange={() => setForm({ ...form, enabled: !form.enabled })} /></Field>
          <div className="full"><Field label="Description"><input className="input-box" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field></div>
        </div>
        {errors.form && <div style={{ color: 'var(--red)', fontSize: 12, marginTop: 8 }}>{errors.form}</div>}
        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8, marginTop: 16 }}>
          <button className="btn" onClick={() => setModal(false)}>Cancel</button>
          <button className="btn btn-primary" onClick={handleCreate} disabled={submitting}>{submitting ? 'Creating...' : 'Create Rule'}</button>
        </div>
      </Modal>
    </div>
  );
}
