// frontend/src/pages/Audit.jsx
import { useState, useEffect, useMemo } from 'react';
import * as api from '../api.js';
import Badge from '../components/Badge.jsx';
import { PageHeader, SkeletonRows, EmptyState, LoadingError } from '../components/Shared.jsx';

const actionGroup = (a) => a?.split('.')[0] || '';

export default function Audit() {
  const [entries, setEntries] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [actorFilter, setActorFilter] = useState('');
  const [actionFilter, setActionFilter] = useState('all');
  const [selected, setSelected] = useState(null);
  const [verifyResult, setVerifyResult] = useState(null);
  const [verifying, setVerifying] = useState(false);

  const fetch = async () => { setLoading(true); try { setEntries(await api.audit.list({ limit: 100 })); setError(null); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { fetch(); }, []);

  const filtered = useMemo(() => entries.filter((e) => {
    const a = actionFilter === 'all' || e.action?.startsWith(actionFilter);
    const ac = !actorFilter || e.actor?.toLowerCase().includes(actorFilter.toLowerCase());
    return a && ac;
  }), [entries, actionFilter, actorFilter]);

  const verify = async () => { setVerifying(true); try { setVerifyResult(await api.audit.verify()); } catch (e) { setVerifyResult({ valid: false, error: e.message }); } finally { setVerifying(false); } };

  const colors = { login: 'var(--purple)', rule: 'var(--cyan)', block: 'var(--red)', backup: 'var(--yellow)', user: 'var(--green)' };

  return (
    <div className="fade-in">
      <PageHeader title="Audit Log" subtitle={`${entries.length} entries — hash-chained`}>
        <a href="/api/v1/audit/export" className="btn">Export JSON</a>
        <button className="btn btn-primary" onClick={verify} disabled={verifying}>{verifying ? '⏳ Verifying...' : '✓ Verify Integrity'}</button>
      </PageHeader>

      {verifyResult && (
        <div className="card" style={{ marginBottom: 12, borderColor: verifyResult.valid ? 'var(--green)' : 'var(--red)', animation: 'fadeSlideIn 0.3s ease' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <span style={{ color: verifyResult.valid ? 'var(--green)' : 'var(--red)', fontSize: 20 }}>{verifyResult.valid ? '✓' : '⚠'}</span>
            <div>
              <div style={{ color: verifyResult.valid ? 'var(--green)' : 'var(--red)', fontWeight: 700, fontSize: 13 }}>{verifyResult.valid ? 'Hash chain intact' : `Integrity violation — ${verifyResult.tampered_count} entries tampered`}</div>
              <div className="cell-dim" style={{ fontSize: 12 }}>{verifyResult.valid ? `All ${verifyResult.total_entries} entries verified` : `First broken at entry #${verifyResult.first_broken_at}`}</div>
            </div>
            <button className="btn" style={{ marginLeft: 'auto' }} onClick={() => setVerifyResult(null)}>✕</button>
          </div>
        </div>
      )}

      <div className="panel" style={{ padding: 12, marginBottom: 12 }}>
        <div style={{ display: 'flex', gap: 8 }}>
          <input className="input-box" style={{ width: 160 }} placeholder="Filter by actor..." value={actorFilter} onChange={(e) => setActorFilter(e.target.value)} />
          <select className="select-box" value={actionFilter} onChange={(e) => setActionFilter(e.target.value)}>
            <option value="all">All Actions</option><option value="login">Login</option><option value="rule">Rule</option><option value="block">Block</option><option value="backup">Backup</option><option value="user">User</option>
          </select>
        </div>
      </div>

      <div className="panel" style={{ overflow: 'hidden', marginBottom: 12 }}>
        {loading ? <SkeletonRows count={5} cols={7} /> : error ? <LoadingError message={error} onRetry={fetch} /> : (
          <table>
            <thead><tr>{['Timestamp','Actor','Action','Resource','IP','Status','Hash'].map((h) => <th key={h}>{h}</th>)}</tr></thead>
            <tbody>
              {filtered.length === 0 ? <tr><td colSpan={7}><EmptyState msg="No audit entries match filters." /></td></tr> : (
                filtered.slice(0, 50).map((e) => (
                  <tr key={e.id} style={{ cursor: 'pointer' }} onClick={() => setSelected(selected?.id === e.id ? null : e)}>
                    <td className="cell-mono cell-dim" style={{ fontSize: 11 }} title={new Date(e.timestamp).toLocaleString()}>{new Date(e.timestamp).toLocaleString()}</td>
                    <td>{e.actor}</td>
                    <td className="cell-mono" style={{ color: colors[actionGroup(e.action)] || 'var(--text)' }}>{e.action}</td>
                    <td className="cell-dim">{e.resource}</td>
                    <td className="cell-mono cell-dim">{e.ip_address || '—'}</td>
                    <td><Badge variant={e.success ? 'success' : 'failed'}>{e.success ? '✓' : '✗'}</Badge></td>
                    <td className="cell-mono" style={{ color: 'var(--text-muted)', fontSize: 11 }} title={e.hash}>{(e.hash || '').slice(0, 12)}...</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        )}
      </div>

      {entries.length > 0 && (
        <div className="card">
          <div style={{ color: 'var(--text-sec)', fontSize: 12, marginBottom: 8 }}>🔗 Hash Chain (last 5)</div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 4, flexWrap: 'wrap' }}>
            {entries.slice(0, 5).map((e) => (
              <div key={e.id} style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                <div style={{ padding: '4px 8px', background: 'var(--bg-elevated)', borderRadius: 4, border: '1px solid var(--bg-border)', fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--text-muted)' }}>{(e.hash || '').slice(0, 8)}</div>
                <span style={{ color: 'var(--text-muted)', fontSize: 10 }}>→</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {selected && (
        <div className="card" style={{ marginTop: 12, animation: 'fadeSlideIn 0.2s ease' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 12 }}>
            <span style={{ color: 'var(--cyan)', fontSize: 12, fontFamily: 'var(--font-mono)' }}>Audit Entry #{selected.id}</span>
            <button onClick={() => setSelected(null)} style={{ background: 'none', border: 'none', color: 'var(--text-sec)', cursor: 'pointer' }}>✕</button>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 8 }}>
            {[['Timestamp', new Date(selected.timestamp).toLocaleString()], ['Actor', selected.actor], ['Action', selected.action], ['Resource', selected.resource], ['IP', selected.ip_address || '—'], ['Status', selected.success ? 'Success' : 'Failed'], ['Hash', selected.hash], ['Previous Hash', selected.previous_hash]].map(([l, v]) => (
              <div key={l} style={{ padding: 8, background: 'var(--bg-elevated)', borderRadius: 6 }}>
                <div style={{ color: 'var(--text-sec)', fontSize: 11 }}>{l}</div>
                <div className="cell-mono" style={{ wordBreak: 'break-all' }}>{v}</div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// frontend/src/routes/audit/+page.svelte
<script>
  import { onMount } from 'svelte';
  import { apiFetch } from '$lib/stores/auth';

  let entries = $state([]);
  let loading = $state(true);
  let error = $state('');
  let filterActor = $state('');
  let filterAction = $state('');
  let chainStatus = $state(null);

  onMount(async () => {
    try {
      const [data, chain] = await Promise.all([
        apiFetch('/audit').catch(() => []),
        apiFetch('/audit/chain').catch(() => null),
      ]);
      entries = Array.isArray(data) ? data : [];
      chainStatus = chain;
    } catch (e) {
      error = e.message;
    } finally {
      loading = false;
    }
  });

  let filtered = $derived.by(() => {
    let result = entries;
    if (filterActor) {
      const q = filterActor.toLowerCase();
      result = result.filter((e) => (e.actor || '').toLowerCase().includes(q));
    }
    if (filterAction) {
      const q = filterAction.toLowerCase();
      result = result.filter((e) => (e.action || '').toLowerCase().includes(q));
    }
    return result;
  });

  function exportAudit() {
    const blob = new Blob([JSON.stringify(entries, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = 'argus-audit-export.json'; a.click();
    URL.revokeObjectURL(url);
  }
</script>

<div class="flex justify-between items-center mb-4 animate-in">
  <div>
    <h1 style="font-family:var(--font-display);font-size:18px;color:var(--text-heading);letter-spacing:2px;text-transform:uppercase;">
      📋 Audit Log
    </h1>
    <span style="font-size:10px;color:var(--text-muted);letter-spacing:1px;">
      {entries.length} ENTRIES
      {#if chainStatus}
        · CHAIN:
        <span class="badge" style={chainStatus.valid ? '' : 'background:var(--red-dim);color:var(--red);'}>
          {chainStatus.valid ? 'VALID' : 'BROKEN'}
        </span>
      {/if}
    </span>
  </div>
  <div class="flex gap-2">
    <button class="btn btn-ghost" onclick={exportAudit}>📥 EXPORT JSON</button>
  </div>
</div>

{#if loading}
  <div style="text-align:center;padding:40px;color:var(--text-muted);">LOADING...</div>
{:else if error}
  <div class="card mb-4">
    <p style="color:var(--red);">⚠ {error}</p>
  </div>
{:else}
  <div class="flex gap-4 mb-4 animate-in">
    <div style="flex:1;max-width:300px;">
      <label style="font-size:10px;text-transform:uppercase;letter-spacing:1px;color:var(--text-muted);display:block;margin-bottom:4px;">Filter Actor</label>
      <input class="input" bind:value={filterActor} placeholder="e.g. admin, system...">
    </div>
    <div style="flex:1;max-width:300px;">
      <label style="font-size:10px;text-transform:uppercase;letter-spacing:1px;color:var(--text-muted);display:block;margin-bottom:4px;">Filter Action</label>
      <input class="input" bind:value={filterAction} placeholder="e.g. create, delete...">
    </div>
  </div>

  {#if chainStatus}
    <div class="card mb-4 animate-in">
      <div class="card-header">
        <div class="indicator" style={chainStatus.valid ? 'background:var(--green);box-shadow:0 0 8px var(--green);' : 'background:var(--red);box-shadow:0 0 8px var(--red);'}></div>
        <h2>Chain Verification</h2>
      </div>
      <div style="display:flex;gap:16px;font-family:var(--font-mono);font-size:11px;">
        <div>
          <span style="color:var(--text-muted);">Status:</span>
          <span style="color:{chainStatus.valid ? 'var(--green)' : 'var(--red)'};margin-left:8px;">
            {chainStatus.valid ? '✓ INTACT' : '✗ BROKEN'}
          </span>
        </div>
        <div>
          <span style="color:var(--text-muted);">Entries:</span>
          <span style="color:var(--text-bright);margin-left:8px;">{chainStatus.count || chainStatus.entries || '—'}</span>
        </div>
        {#if chainStatus.last_hash}
          <div>
            <span style="color:var(--text-muted);">Last Hash:</span>
            <span style="color:var(--text-bright);margin-left:8px;font-size:10px;">{chainStatus.last_hash.slice(0, 16)}…</span>
          </div>
        {/if}
      </div>
    </div>
  {/if}

  <div class="card animate-in">
    <table class="data-table">
      <thead>
        <tr>
          <th>Time</th>
          <th>Actor</th>
          <th>Action</th>
          <th>Resource</th>
          <th>Details</th>
          <th>Integrity</th>
        </tr>
      </thead>
      <tbody>
        {#each filtered as entry}
          <tr>
            <td style="color:var(--text-muted);font-size:11px;">
              {entry.timestamp ? new Date(entry.timestamp).toLocaleString() : '—'}
            </td>
            <td style="color:var(--text-bright);">{entry.actor || 'system'}</td>
            <td>
              {#if entry.action === 'create' || entry.action === 'allow'}
                <span class="badge allow">{entry.action}</span>
              {:else if entry.action === 'delete' || entry.action === 'deny'}
                <span class="badge deny">{entry.action}</span>
              {:else}
                <span class="badge info">{entry.action || '—'}</span>
              {/if}
            </td>
            <td style="color:var(--text-body);">{entry.resource || '—'}</td>
            <td style="color:var(--text-body);font-size:11px;max-width:300px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;">
              {entry.details || '—'}
            </td>
            <td>
              {#if entry.integrity_ok === false}
                <span class="badge deny">INVALID</span>
              {:else}
                <span class="badge on">OK</span>
              {/if}
            </td>
          </tr>
        {:else}
          <tr>
            <td colspan="6" style="text-align:center;padding:32px;color:var(--text-muted);">
              {filterActor || filterAction ? 'NO ENTRIES MATCH YOUR FILTERS' : 'NO AUDIT ENTRIES'}
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
{/if}
