// frontend/src/pages/Dashboard.jsx
import { useState, useEffect, useRef, useCallback } from 'react';
import { LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend } from 'recharts';
import * as api from '../api.js';
import { PageHeader, LoadingError } from '../components/Shared.jsx';

export default function Dashboard() {
  const [stats, setStats] = useState(null);
  const [error, setError] = useState(null);
  const [liveEvents, setLiveEvents] = useState([]);
  const [packetWindow, setPacketWindow] = useState([]);
  const windowRef = useRef([]);

  const fetchStats = useCallback(async () => {
    try {
      const s = await api.stats.get();
      setStats(s);
      setError(null);
      const now = new Date().toLocaleTimeString();
      windowRef.current = [...windowRef.current.slice(-59), { time: now, allowed: s.packets_allowed || 0, dropped: s.packets_dropped || 0 }];
      setPacketWindow([...windowRef.current]);
    } catch (e) {
      setError(e.message);
    }
  }, []);

  useEffect(() => {
    fetchStats();
    const interval = setInterval(fetchStats, 5000);

    const wsCleanup = api.connectWebSocket((msg) => {
      const addEvent = (severity, text) => setLiveEvents((prev) => [...prev.slice(-49), { time: new Date().toLocaleTimeString(), msg: text, severity }]);

      if (msg.event_type === 'stats' && msg.data) {
        setStats(msg.data);
      } else if (msg.event_type === 'connection' && msg.data) {
        addEvent('info', `Connection: ${msg.data.src_ip} → ${msg.data.dst_ip} (${msg.data.state})`);
      } else if (msg.event_type === 'alert' && msg.data) {
        addEvent(msg.data.severity || 'warning', msg.data.message || 'Alert fired');
      }
    });

    return () => {
      clearInterval(interval);
      if (wsCleanup) wsCleanup();
    };
  }, [fetchStats]);

  const protoData = [
    { name: 'TCP', value: 45 },
    { name: 'UDP', value: 22 },
    { name: 'ICMP', value: 8 },
  ];

  return (
    <div className="fade-in">
      <PageHeader title="Dashboard" subtitle="Real-time network overview" />

      {error && <LoadingError message={error} onRetry={fetchStats} />}

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 12, marginBottom: 20 }}>
        {[
          { label: 'Packets Allowed', value: stats?.packets_allowed?.toLocaleString() || '—', color: 'var(--green)', icon: '📦' },
          { label: 'Packets Dropped', value: stats?.packets_dropped?.toLocaleString() || '—', color: 'var(--red)', icon: '🚫' },
          { label: 'Active Connections', value: stats?.active_connections || '—', color: 'var(--cyan)', icon: '🔗' },
          { label: 'Blocked IPs', value: stats?.blocked_ips || '—', color: 'var(--yellow)', icon: '🌐' },
        ].map((c) => (
          <div key={c.label} className="card">
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 8 }}>
              <span style={{ color: 'var(--text-sec)', fontSize: 12 }}>{c.icon} {c.label}</span>
            </div>
            <div style={{ fontFamily: 'var(--font-mono)', fontSize: 28, fontWeight: 700 }}>{c.value}</div>
          </div>
        ))}
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 20 }}>
        <div className="card">
          <div style={{ color: 'var(--text-sec)', fontSize: 12, marginBottom: 12 }}>📈 Packet Rate</div>
          {packetWindow.length > 0 ? (
            <ResponsiveContainer width="100%" height={200}>
              <LineChart data={packetWindow}>
                <CartesianGrid strokeDasharray="3 3" stroke="var(--bg-border)" />
                <XAxis dataKey="time" stroke="var(--text-muted)" tick={{ fontSize: 10 }} />
                <YAxis stroke="var(--text-muted)" tick={{ fontSize: 10 }} />
                <Tooltip contentStyle={{ background: 'var(--bg-panel)', border: '1px solid var(--bg-border)', borderRadius: 8, color: 'var(--text)' }} />
                <Line type="monotone" dataKey="allowed" stroke="var(--green)" strokeWidth={2} dot={false} isAnimationActive animationDuration={800} />
                <Line type="monotone" dataKey="dropped" stroke="var(--red)" strokeWidth={2} dot={false} isAnimationActive animationDuration={800} />
              </LineChart>
            </ResponsiveContainer>
          ) : (
            <div style={{ height: 200, display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-muted)', fontSize: 13 }}>Collecting data...</div>
          )}
        </div>

        <div className="card">
          <div style={{ color: 'var(--text-sec)', fontSize: 12, marginBottom: 12 }}>🍩 Protocol Distribution</div>
          <ResponsiveContainer width="100%" height={200}>
            <PieChart>
              <Pie data={protoData} dataKey="value" cx="50%" cy="50%" outerRadius={70} innerRadius={35} isAnimationActive animationDuration={800}>
                {protoData.map((e, i) => <Cell key={e.name} fill={['var(--cyan)', 'var(--purple)', 'var(--yellow)'][i]} />)}
              </Pie>
              <Tooltip contentStyle={{ background: 'var(--bg-panel)', border: '1px solid var(--bg-border)', borderRadius: 8, color: 'var(--text)' }} />
              <Legend wrapperStyle={{ fontSize: 11, color: 'var(--text-sec)' }} />
            </PieChart>
          </ResponsiveContainer>
        </div>
      </div>

      <div className="card" style={{ marginBottom: 20 }}>
        <div style={{ color: 'var(--text-sec)', fontSize: 12, marginBottom: 12 }}>⚡ Live Event Feed</div>
        <div style={{ maxHeight: 240, overflowY: 'auto' }}>
          {liveEvents.length === 0 ? (
            <div style={{ color: 'var(--text-muted)', textAlign: 'center', padding: 24 }}>Waiting for events...</div>
          ) : (
            liveEvents.slice(-15).map((e, i) => (
              <div key={i} style={{ display: 'flex', gap: 8, padding: '6px 0', borderBottom: '1px solid var(--bg-border)', alignItems: 'center' }}>
                <span style={{ color: 'var(--text-muted)', fontSize: 11, fontFamily: 'var(--font-mono)', minWidth: 70 }}>{e.time}</span>
                <span className="badge" style={{ background: e.severity === 'critical' ? 'var(--red)' : e.severity === 'warning' ? 'var(--yellow)' : 'var(--cyan)', color: e.severity === 'critical' ? '#fff' : '#000' }}>{e.severity || 'info'}</span>
                <span style={{ fontSize: 12, fontFamily: 'var(--font-mono)' }}>{e.msg}</span>
              </div>
            ))
          )}
        </div>
      </div>

      <div className="card">
        <div style={{ color: 'var(--text-sec)', fontSize: 12, marginBottom: 12 }}>🔋 System Health</div>
        {[
          { label: 'API', status: stats ? 'ONLINE' : '—', color: stats ? 'var(--green)' : 'var(--red)' },
          { label: 'eBPF', status: stats?.packets_allowed != null ? 'ACTIVE' : '—', color: stats?.packets_allowed != null ? 'var(--green)' : 'var(--red)' },
          { label: 'DB', status: 'IN-MEMORY', color: 'var(--cyan)' },
          { label: 'WebSocket', status: 'CONNECTED', color: 'var(--green)' },
        ].map((s) => (
          <div key={s.label} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 0', borderBottom: '1px solid var(--bg-border)' }}>
            <span className="live-dot" style={{ background: s.color, animation: 'livePulse 2s infinite' }} />
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 12 }}>{s.label}</span>
            <span style={{ color: 'var(--text-sec)', fontSize: 12, marginLeft: 'auto' }}>● {s.status}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

// frontend/src/routes/dashboard/+page.svelte
<script>
  import { onMount } from 'svelte';
  import { apiFetch, authToken } from '$lib/stores/auth';
  import { liveStats, liveConnections, wsConnected, connectWebSocket, disconnectWebSocket } from '$lib/stores/live';
  import { Line, Bar, Doughnut } from 'svelte-chartjs';
  import {
    Chart as ChartJS,
    CategoryScale,
    LinearScale,
    PointElement,
    LineElement,
    BarElement,
    ArcElement,
    Title,
    Tooltip,
    Legend,
    Filler
  } from 'chart.js';

  ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, BarElement, ArcElement, Title, Tooltip, Legend, Filler);

  let stats = $state({ packets_allowed: 0, packets_dropped: 0, active_connections: 0, blocked_ips: 0, rate_limit_buckets: 0 });
  let rules = $state([]);
  let conns = $state([]);
  let loading = $state(true);

  let trafficHistory = $state({ allowed: Array(20).fill(0), dropped: Array(20).fill(0), labels: Array(20).fill('') });
  let blockedIPs = $state({ labels: [], data: [] });
  let protoDistribution = $state({ labels: ['TCP', 'UDP', 'ICMP', 'Other'], data: [0, 0, 0, 0] });

  let wsFailed = $state(false);

  const chartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: { legend: { labels: { color: '#8b949e', font: { family: "'JetBrains Mono', monospace", size: 10 } } } },
    scales: { x: { ticks: { color: '#5c6370', maxTicksLimit: 10 }, grid: { color: 'rgba(30,37,51,0.5)' } }, y: { ticks: { color: '#5c6370' }, grid: { color: 'rgba(30,37,51,0.5)' }, beginAtZero: true } }
  };

  function updateTrafficHistory(allowed, dropped) {
    trafficHistory.allowed = [...trafficHistory.allowed.slice(1), allowed];
    trafficHistory.dropped = [...trafficHistory.dropped.slice(1), dropped];
    const now = new Date();
    trafficHistory.labels = [...trafficHistory.labels.slice(1), now.toLocaleTimeString('en-US', { hour12: false })];
  }

  function computeBlockedIPs(connections) {
    const ipCounts = {};
    for (const c of connections) {
      if (c.state === 'closed' || c.state === 'closing') {
        ipCounts[c.src_ip] = (ipCounts[c.src_ip] || 0) + 1;
      }
    }
    const sorted = Object.entries(ipCounts).sort((a, b) => b[1] - a[1]).slice(0, 8);
    blockedIPs = { labels: sorted.map(([ip]) => ip), data: sorted.map(([, n]) => n) };
  }

  function computeProtoDistribution(connections) {
    let tcp = 0, udp = 0, icmp = 0, other = 0;
    for (const c of connections) {
      const p = (c.protocol || '').toLowerCase();
      if (p === 'tcp') tcp++;
      else if (p === 'udp') udp++;
      else if (p === 'icmp') icmp++;
      else other++;
    }
    protoDistribution = { labels: ['TCP', 'UDP', 'ICMP', 'Other'], data: [tcp, udp, icmp, other] };
  }

  async function pollData() {
    try {
      const [s, r, c] = await Promise.all([
        apiFetch('/stats'),
        apiFetch('/rules'),
        apiFetch('/connections'),
      ]);
      stats = s;
      rules = r;
      conns = c;
      updateTrafficHistory(s.packets_allowed, s.packets_dropped);
      computeBlockedIPs(c);
      computeProtoDistribution(c);
    } catch (e) {
      console.error('Dashboard fetch failed:', e);
    }
  }

  onMount(() => {
    let token;
    authToken.subscribe((v) => { token = v; })();

    pollData().then(() => { loading = false; });

    if (token) {
      connectWebSocket(token);
      const unsubWs = wsConnected.subscribe((connected) => {
        if (connected) wsFailed = false;
      });

      const unsubStats = liveStats.subscribe((s) => {
        if (s) {
          stats = s;
          updateTrafficHistory(s.packets_allowed, s.packets_dropped);
        }
      });

      const unsubConns = liveConnections.subscribe((c) => {
        if (c && c.length) {
          conns = c;
          computeBlockedIPs(c);
          computeProtoDistribution(c);
        }
      });

      setTimeout(() => {
        if (!$wsConnected) wsFailed = true;
      }, 4000);

      const interval = setInterval(() => {
        if (wsFailed) pollData();
      }, 5000);

      return () => {
        disconnectWebSocket();
        clearInterval(interval);
        unsubWs();
        unsubStats();
        unsubConns();
      };
    } else {
      const interval = setInterval(pollData, 5000);
      return () => clearInterval(interval);
    }
  });
</script>

{#if loading}
  <div style="display:flex;align-items:center;justify-content:center;height:60vh;color:var(--text-muted);">
    <span style="animation:pulse 2s infinite;">▌&nbsp;INITIALIZING...</span>
  </div>
{:else}
  <div class="flex items-center justify-between mb-4 animate-in">
    <div>
      <h1 style="font-family:var(--font-display);font-size:18px;color:var(--text-heading);letter-spacing:2px;text-transform:uppercase;">
        ⚡ Dashboard
      </h1>
      <span style="font-size:10px;color:var(--text-muted);letter-spacing:1px;">
        LIVE MONITORING
        {#if $wsConnected}
          <span class="status-dot online" style="display:inline-block;margin-left:8px;"></span> WS
        {:else if wsFailed}
          <span class="status-dot warn" style="display:inline-block;margin-left:8px;"></span> POLLING
        {/if}
      </span>
    </div>
  </div>

  <div class="stat-grid animate-in">
    <div class="stat-card green">
      <div class="stat-value">{stats.packets_allowed.toLocaleString()}</div>
      <div class="stat-label">Packets Allowed</div>
    </div>
    <div class="stat-card red">
      <div class="stat-value">{stats.packets_dropped.toLocaleString()}</div>
      <div class="stat-label">Packets Dropped</div>
    </div>
    <div class="stat-card cyan">
      <div class="stat-value">{stats.active_connections}</div>
      <div class="stat-label">Active Connections</div>
    </div>
    <div class="stat-card yellow">
      <div class="stat-value">{stats.blocked_ips}</div>
      <div class="stat-label">Blocked IPs</div>
    </div>
    <div class="stat-card purple">
      <div class="stat-value">{stats.rate_limit_buckets}</div>
      <div class="stat-label">Rate Limit Buckets</div>
    </div>
  </div>

  <div class="grid grid-cols-2 gap-4 mb-4 animate-in" style="animation-delay:0.1s;">
    <div class="card col-span-2">
      <div class="card-header">
        <div class="indicator"></div>
        <h2>Traffic — Packets Allowed vs Dropped</h2>
      </div>
      <div style="height: 240px;">
        <Line
          data={{
            labels: trafficHistory.labels,
            datasets: [
              { label: 'Allowed', data: trafficHistory.allowed, borderColor: '#3fb950', backgroundColor: 'rgba(63,185,80,0.1)', fill: true, tension: 0.3, pointRadius: 0 },
              { label: 'Dropped', data: trafficHistory.dropped, borderColor: '#f85149', backgroundColor: 'rgba(248,81,73,0.1)', fill: true, tension: 0.3, pointRadius: 0 }
            ]
          }}
          options={chartOptions}
        />
      </div>
    </div>

    <div class="card">
      <div class="card-header">
        <div class="indicator" style="background:var(--purple);box-shadow:0 0 8px var(--purple);"></div>
        <h2>Protocol Distribution</h2>
      </div>
      <div style="height: 240px;">
        <Doughnut
          data={{
            labels: protoDistribution.labels,
            datasets: [{ data: protoDistribution.data, backgroundColor: ['#39d0ff', '#a371f7', '#f0883e', '#5c6370'], borderColor: 'var(--bg-card)', borderWidth: 2 }]
          }}
          options={{ responsive: true, maintainAspectRatio: false, plugins: { legend: { position: 'bottom', labels: { color: '#8b949e', font: { family: "'JetBrains Mono', monospace", size: 10 }, padding: 12 } } } }}
        />
      </div>
    </div>

    <div class="card">
      <div class="card-header">
        <div class="indicator" style="background:var(--red);box-shadow:0 0 8px var(--red);"></div>
        <h2>Top Blocked IPs</h2>
      </div>
      <div style="height: 240px;">
        {#if blockedIPs.labels.length > 0}
          <Bar
            data={{
              labels: blockedIPs.labels,
              datasets: [{ label: 'Blocks', data: blockedIPs.data, backgroundColor: 'rgba(248,81,73,0.6)', borderColor: '#f85149', borderWidth: 1, borderRadius: 2 }]
            }}
            options={{
              indexAxis: 'y',
              responsive: true,
              maintainAspectRatio: false,
              plugins: { legend: { display: false } },
              scales: { x: { ticks: { color: '#5c6370' }, grid: { color: 'rgba(30,37,51,0.5)' } }, y: { ticks: { color: '#8b949e', font: { family: "'JetBrains Mono', monospace", size: 9 } }, grid: { display: false } } }
            }}
          />
        {:else}
          <div style="display:flex;align-items:center;justify-content:center;height:100%;color:var(--text-muted);font-size:11px;">
            NO BLOCKED IPs YET
          </div>
        {/if}
      </div>
    </div>
  </div>

  <div class="grid grid-cols-2 gap-4 animate-in" style="animation-delay: 0.15s;">
    <div class="card">
      <div class="card-header">
        <div class="indicator"></div>
        <h2>Firewall Rules ({rules.length})</h2>
      </div>
      <div style="max-height: 300px; overflow-y: auto;">
        {#if rules.length === 0}
          <p style="color:var(--text-muted);font-size:12px;padding:16px 0;text-align:center;">NO RULES CONFIGURED</p>
        {:else}
          {#each rules.slice(0, 15) as rule}
            <div style="display:flex;align-items:center;justify-content:space-between;padding:6px 0;border-bottom:1px solid var(--border-dim);font-size:12px;" class="animate-in">
              <span style="font-family:var(--font-mono);">
                {#if rule.action === 'deny'}
                  <span class="badge deny">DENY</span>
                {:else if rule.action && rule.action.startsWith('rate-limit')}
                  <span class="badge warn">LIMIT</span>
                {:else}
                  <span class="badge allow">ALLOW</span>
                {/if}
              </span>
              <span style="color:var(--text-body);flex:1;margin-left:12px;">{rule.name}</span>
              <span style="color:var(--text-muted);font-size:11px;">{rule.direction}</span>
              <span class="badge" class:on={rule.enabled} class:off={!rule.enabled}>
                {rule.enabled ? 'ON' : 'OFF'}
              </span>
            </div>
          {/each}
        {/if}
      </div>
    </div>

    <div class="card">
      <div class="card-header">
        <div class="indicator" style="background:var(--green);box-shadow:0 0 8px var(--green),0 0 16px rgba(63,185,80,0.3);"></div>
        <h2>Active Connections ({conns.length})</h2>
      </div>
      <div style="max-height: 300px; overflow-y: auto;">
        {#if conns.length === 0}
          <p style="color:var(--text-muted);font-size:12px;padding:16px 0;text-align:center;">NO ACTIVE CONNECTIONS</p>
        {:else}
          {#each conns.slice(0, 15) as conn}
            <div style="display:flex;align-items:center;gap:8px;padding:6px 0;border-bottom:1px solid var(--border-dim);font-size:11px;font-family:var(--font-mono);">
              <span style="color:var(--text-body);">{conn.src_ip}:{conn.src_port}</span>
              <span style="color:var(--text-muted);">→</span>
              <span style="color:var(--text-body);">{conn.dst_ip}:{conn.dst_port}</span>
              <span style="margin-left:auto;color:var(--cyan);">{conn.state ? conn.state.toUpperCase() : '?'}</span>
            </div>
          {/each}
        {/if}
      </div>
    </div>
  </div>
{/if}
